### ISSUE TITLE
Improve output directory structure

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#132]
Improve output directory structure

Currently:
- atm/
  - 180x360_aave/
    - clim/
      - 100yr/
      - 250yr/
      - 50yr/
    - clim_atm_monthly_diurnal_8xdaily_180x360_aave/
      - 100yr/
      - 250yr/
      - 50yr/
    - ts/
      - daily/
      - monthly/
  - glb/
    - ts/
      - monthly/

**Comment by golaz** [comment]
The problem is that the sub-directory name `clim_atm_monthly_diurnal_8xdaily_180x360_aave` duplicates unnecessary information (`atm`, `180x360_aave`).

One possible alternative would be

- atm/
  - 180x360_aave/
     -  clim/
        - monthly/   
           - 100yr/
           - 250yr/
            - 50yr/
         - monthly_diurnal_8xdaily/
            - 100yr/
            -  250yr/
            -  50yr/
     -  ts/
        -  daily/
        -  monthly/
     -  glb/
        -  ts/
           -  monthly/

But strictly speaking, the files under `clim/monthly` are not all monthly since ncclimo also generates seasonal and annual files. But maybe that's ok.

**Comment by chengzhuzhang** [comment]
For TC tracking files, we could have a directory the atm/tc.
Also need a atm/arm-sites (optional) directory for high-frequency ARM-site output (but the name list variables are not available as default)
For cmorized files, it could be atm/180x360_aave/ts_cmip with sub directories /6hrly /daily /monthly. Same for other component lnd, ocean, sea-ice... Because regular CMORizing process re-org files in a CMIP specific directory system, we could have a separate system for CMORized files, which is another possibility

**Comment by forsyth2** [comment]
@golaz @chengzhuzhang I'm thinking the second alternative might be best. If you both agree with that, I can start changing the directory structure.

**Second alternative**

- atm/
  - 180x360_aave/
     -  clim/
         - 100yr/
         - 250yr/
         - 50yr/
       - clim_diurnal_8xdaily/
          - 100yr/
          -  250yr/
          -  50yr/
     -  ts/
        -  daily/
        -  monthly/
   -  glb/
      -  ts/
         -  monthly/
   - tc/

**Comment by golaz** [comment]
@forsyth2 : I like this second alternative as well.

Let's use the `frequency` parameter to determine the destination directory. This will decouple the sub-section name from the directory structure and thus should be more robust.
