### ISSUE TITLE
ncclimo call may need to be fixed for land variable regridding

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/zppy#220]
Better discription of this issue:
> The figure looks about right in that it has color in all the right places where `landfrac > 0.0`. So the "landmask" appears to be correct. However, the scripts were never told that this was ELM data so every native gridcell was assumed to have `landfrac == 1.0` and the SGS routines were not employed during regridding. The differences are typically not large (a few percent at most) in the global mean, and so difficult to detect by eye.
> 

An example provided on https://github.com/E3SM-Project/zppy/issues/220#issuecomment-1076604080
![image](https://user-images.githubusercontent.com/13056557/159048476-36741f27-1aae-44fd-a1d3-5f9b2e915cc3.png)

/lcrc/group/e3sm/ac.forsyth2/E3SMv2/v2.LR.historical_0201/post/lnd/180x360_aave/ts/monthly/5yr/FSH_185001_185412.nc
![Screen Shot 2022-03-18 at 9 58 50 AM](https://user-images.githubusercontent.com/13056557/159048619-f878a8ae-da87-4cad-9890-bc21293396c0.png)

**Comment by chengzhuzhang** [comment]
Hi @czender , I'm trying to look into this issue, both e3sm_to_cmip and zppy produced land model time-series give land variables with inaccurate ocean mask, (i.g., artifacts over Indonesian archipelago). e3sm_to_cmip does include the sgs_frc flag to include land-fraction. So I'm wondering maybe the missing -P elm/cam (or --model) when invoking ncclimo might be the culprit?

**Comment by czender** [comment]
@chengzhuzhang it's hard for me to tell from the images what might be going wrong. Please point me to a raw file directory and to the regridded timeseries file (created from that raw data) that contains the inaccurate ocean mask. Also the ncclimo command used to generate the timeseries file would be helpful, though presumably I can obtain that from the `history` attribute.

**Comment by chengzhuzhang** [comment]
Hey Charlie. I looked at the land sea mask, yes, it does appear that there are small fractions of land outside of the coastal areas being visualized by the ploting tool. In this case i think we probably don't need to do any changes for ncclimo calls. 
Another question i have is that `-P elm` explicitly takes in account `sgs_frac`. In this particular zppy call https://github.com/E3SM-Project/zppy/blob/a5d9ec5104447c8e4ff78add1f89b96f6cbff9c0/zppy/templates/ts.bash#L61: should we explicitly add `-P elm`, otherwise, it will treat sgs_frc as 1 everywhere?

**Comment by czender** [comment]
Ahhh. Now I see that there is a sub-gridscale issue. The regridded timeseries you pointed me to does not correctly account for sub-gridscale (SGS) areas, so the values in gridcells with fractional land **are incorrect**. When regridding ELM or MPAS-Seaice data, or, more generally, any dataset with fractional areas, one must invoke SGS algorithms. In this case, `ncclimo`  itself calls the regridder so one must pass that option to `ncclimo`. This has been true since...forever. Unfortunately I think the regridding must be redone to get the correct answers for ELM data. Please doublecheck the `zppy` calls for MPAS-Seaice too. 
You were exactly right to note above that `e3sm2cmip` explicitly includes `sgs_frc` so why doesn't `zppy`? Well, `zppy` should pass `-P elm` to `ncclimo`, or `--sgs_frc=landfrac`. The differences between them are subtle, and have to do with what variables appear in the output file. The main difference is that `-P elm` outputs `area` in ELM-native units of km2, whereas  `--sgs_frc=landfrac` outputs `area` in steradians, which are more portable units (and are CMIP-compliant). It is always safe to call `ncclimo` or `ncremap` with `-P mdl_nm` where `mdl_nm` is `elm` or `eam` or `mpasseaice` or whatever. Let me know if you have any questions...

**Comment by rljacob** [comment]
What are you expecting to see in the above figure?

**Comment by czender** [comment]
The figure looks about right in that it has color in all the right places where `landfrac > 0.0`. So the "landmask" appears to be correct. However, the scripts were never told that this was ELM data so every native gridcell was assumed to have `landfrac == 1.0` and the SGS routines were not employed during regridding. The differences are typically not large (a few percent at most) in the global mean, and so difficult to detect by eye. 

I was thinking that to make this type of error less frequent, the regridder could spot check each input file for indications that it is an ELM or MPAS-Seaice dataset, e.g., by looking for `landfrac` or `timeMonthly_avg_iceAreaCell`. If such an SGS variable is present and SGS-options were not invoked, the regridder could print a WARNING or even an ERROR. Thoughts?

**Comment by czender** [comment]
Good point @minxu74. Any temperature field is an excellent diagnostic of this in both ELM and MPAS-Seaice. The raw E3SM input data will always have T > 150 K. If after post-processing T < 150 K, then omission of SGS treatment during regridding is a likely cause. This could be done as a sanity check prior to publication.

**Comment by chengzhuzhang** [comment]
Great information. Thank you for the discussion! The TSA field does show invalid small values (<150 K) near coastal lines when SGS weighting is not applied. Following shows snapshots from both cases.

with sgs, displayed value range (230 to 306 K)
![Screen Shot 2022-03-23 at 10 13 57 AM](https://user-images.githubusercontent.com/13056557/159757495-a5d375e9-cff5-4c49-84e3-fd715de24374.png)

without sgs, displayed value range (10e-11 to 306 K)
![Screen Shot 2022-03-23 at 10 12 20 AM](https://user-images.githubusercontent.com/13056557/159757673-b8c92a1d-d099-4b0b-ab10-881251d38d1a.png)




@czender One trivial fact I noticed in the global attributes of both processed time-series, there is one line
`comment = "NOTE: None of the variables are weighted by land fraction!`
This should come from the ELM global attribute. It might be confusing to be included in nco processed files with sgs turned on. At least this NOTE can be written as "NOTE: None of the variables are weighted by land fraction **in original model output**!"?

And as you mentioned earlier, I think it is worthwhile to include at least a warning, if --sgs_frac is not applied when it should be.

**Comment by czender** [comment]
@chengzhuzhang the ELM attribute you refer to, "NOTE: None..." is correct for both the raw ELM data and the correctly regridded data. This topic can be confusing, partly due to the semantics of what you think "weighted by land fraction" means in the context of regridding. Think of it this way: the raw data and the correctly SGS-regridded data are identical (and conserve fluxes with mapfile used here) except for the grids they are on. One should interpret the "weighted by" in the message to mean that the values are not weighted by `landfrac`, i.e., the values apply only over the valid fraction of the gridcell and are only gridcell-means where` landfrac == 1`. So we should preserve the ELM message. In fact, the SGS-algorithms as designed to ensure the validity of the ELM message.

I will add a warning when SGS algorithms are not invoked on datasets that contain `landfrac` or `timeMonthly_avg_iceAreaCell` (and possibly some CESM equivalents like `aice` for CICE).

**Comment by chengzhuzhang** [comment]
@czender Thank you for enlightening me. It makes sense to me now!
I will have a RP to fix the ncclimo calls here in zppy.
By briefly checking MPAS-A, I think @xylar has taken care of adding -P mld_nm. That should be good.
I'm not completely sure if sgs was included in data published with e3sm_to_cmip (especially earlier datasets). I will have to check.

**Comment by czender** [comment]
Sounds good. The temperature field is a good way to check.
