### ISSUE TITLE
Fix `ImportError: cannot import name 'environmentfilter' from 'jinja2'`

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#318]
Fix `ImportError: cannot import name 'environmentfilter' from 'jinja2'`. This error occurs when running `make html`.

**Comment by forsyth2** [comment]
@tomvothecoder I'm not sure what's going on here. https://github.com/readthedocs/readthedocs.org/issues/9038 suggests setting `Jinja2<3.1` but https://github.com/E3SM-Project/zppy/blob/main/conda/dev.yml#L9 was working before with `jinja2=3.1.2`. Do you have any ideas? Thanks!

**Comment by tomvothecoder** [comment]
I'm not sure why `jinja=3.1.2` doesn't work anymore, although _it shouldn't have worked in the first place_ because `environmentfilter` is no longer in the `__init__.py` file as of 3.1.x (https://github.com/pallets/jinja/blob/3.1.0/src/jinja2/__init__.py).

I suggest following the solution in the post you cited, which is to downgrade to `jinja=3.0.3`. This version has `environmentfilter` in `__init__.py`.
https://github.com/pallets/jinja/blob/3.0.3/src/jinja2/__init__.py#L18

**Comment by forsyth2** [comment]
Thanks @tomvothecoder. I am able to build the docs on Chrysalis with no pre-commit failures.

Unfortunately, I just pushed the change at #321, and ran into a pre-commit failure: https://github.com/E3SM-Project/zppy/actions/runs/3193043182/jobs/5211197145

```
AttributeError: 'EntryPoints' object has no attribute 'get'

Error: The process '/opt/hostedtoolcache/Python/3.7.14/x64/bin/pre-commit' failed with exit code 1
```

**Comment by forsyth2** [comment]
Thanks @tomvothecoder. Also looking into https://github.com/python/importlib_metadata/issues/406 and https://github.com/PyCQA/flake8/issues/1701
