### ISSUE TITLE
zppy creates negative values for TREFHT

### ISSUE THREAD

**Issue by araman2** [E3SM-Project/zppy#356]
I used load_e3sm_unified_1.7.0_compy.sh to run zppy in compy. The post-processing creates pdf and json files with negative TREFHT values and strange spatial patterns in climatological maps: 

Output pdf and json files for TREFHT: /compyfs/www/rama225/v2.LR.abrupt-1970-aerosol_nco5xSO4SO2_0301/zppy_output/v2.LR.abrupt-1970-aerosol_nco5xSO4SO2_0301_production/e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_0301-0320/area_mean_time_series/TREFHT

However, netcdf files associated with global climatological mean time series for every 50 years show non-negative values: /compyfs/rama225/v2.LR.abrupt-1970-aerosol_nco5xSO4SO2_0301/zppy_output/post/atm/glb/ts/monthly/50yr

Run script for compy can be found here: /compyfs/rama225/v2.LR.abrupt-1970-aerosol_nco5xSO4SO2_0301/zppy_scripts/zppy_5xs04.cfg

I also see strange patterns in seasonal climatological maps for multiple variables. For example, variables PS, TREFHT show strange spatial patterns: /compyfs/rama225/v2.LR.abrupt-1970-aerosol_nco5xSO4SO2_0301/zppy_output/post/atm/180x360_aave/clim/50yr

**Comment by chengzhuzhang** [comment]
Hi @araman2, Thank you for reporting this issue. This is an known issue with the e3sm_unified 1.7.0 deployment on Compy. Users on Compy were suggested to use 1.6.0 version of e3sm_unified to by pass this issue. The team is working on a new E3SM_unified version, which will soon replace the 1.7.0. Can you please replace with e3sm_unified activation path (/share/apps/E3SM/conda_envs/test_e3sm_unified_1.8.0rc1_compy.sh) and try again? sorry about the inconvenience.

**Comment by araman2** [comment]
Thanks. I'm trying using version 1.6. But it is not creating figures or json files in the /compyfs/www/username directory. My code is located here: /compyfs/rama225/v2.LR.abrupt-1970-aerosol_nco5xSO4SO2_0301/zppy_scripts/zppy_5xSO4_v2.cfg
It does create netcdf files.

**Comment by araman2** [comment]
@chengzhuzhang: I tried test_e3sm_unified_1.8.0rc1_compy.sh. TREFHT is still negative. Is there a version of e3sm_unified in compy that produces correct plots for TREFHT? I also tried version 1.6.

**Comment by forsyth2** [comment]
Adding the following to your `cfg` removes the errors for me: 

1. 
```
[e3sm_diags_vs_model]
active = False
```
This has to be added because E3SM Unified 1.5.1 uses a non-backwards compatible version of `zppy` (https://github.com/E3SM-Project/zppy/releases/tag/v1.1.0). `zppy v1.x.x` defaulted all tasks to `active = True`, so if a task was not specified, it would be assumed to be active. However, no `years` were provided so `zppy` failed here for you.

This default is no longer the case as of `zppy v2.0.0` (https://github.com/E3SM-Project/zppy/releases/tag/v2.0.0).  In fact, the `e3sm_diags_vs_model` task doesn't even exist anymore (as of `zppy v2.1.0` -- https://github.com/E3SM-Project/zppy/releases/tag/v2.1.0).

2. Set `years = "300-450",` in `[global_time_series]`. Note however that I now get the following:
```
...skipping because of dependency status file missing
   /compyfs/fors729/zppy_support/v2.LR.0.25xGHG_0301/zppy_output_v1.5.1/post/scripts/ts_atm_monthly_glb_0300-0309-0010.status
```
I'm not sure why it's looking only up to `309` instead of `310`....

> I tried test_e3sm_unified_1.8.0rc1_compy.sh. TREFHT is still negative.

As discussed in #348, this was unfortunately not fixed in E3SM Unified 1.8. Hopefully it will be included in the next Unified release.

**Comment by forsyth2** [comment]
As indicated, in https://github.com/E3SM-Project/zppy/discussions/348#discussioncomment-4614526 this should be resolved with the latest Unified environment.

**Comment by forsyth2** [comment]
> As indicated in [#348 (reply in thread)](https://github.com/E3SM-Project/zppy/discussions/348#discussioncomment-4614526), this should be resolved with the latest Unified environment.

@araman2 Have you been able to run `zppy` successfully using the latest Unified environment? If so, I'll close this issue.

**Comment by chengzhuzhang** [comment]
This is resolved with latest e3sm_unified env with nco updates.
