### ISSUE TITLE
Explicitly specifying 'machine' in cfg file fails

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zppy#383]
I'm trying to run zppy on cori-haswell (because its life has been extended and pm is down).

Since, E3SM unified is no longer available on cori-knl login nodes (?), I'm working in an interactive session on haswell:

```
salloc --nodes 1 --qos interactive --time 04:00:00 --constraint haswell
source /global/common/software/e3sm/anaconda_envs/load_latest_e3sm_unified_cori-haswell.sh
cd ~/E3SM/QBO/scripts
```

First try
```
zppy -c post.workdir.1.cfg
Configuration file validation passed.
Traceback (most recent call last):
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.8.0_cori-haswell/bin/zppy", line 10, in <module>
    sys.exit(main())
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.8.0_cori-haswell/lib/python3.10/site-packages/zppy/__main__.py", line 84, in main
    machine_info = MachineInfo(machine=machine)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.8.0_cori-haswell/lib/python3.10/site-packages/mache/machine_info.py", line 75, in __init__
    raise ValueError('Unable to discover machine from host name')
ValueError: Unable to discover machine from host name
```

Second try. I added the following in the [default] section of my cfg

`machine = cori-haswell`

and run zppy again

```
zppy -c post.workdir.1.cfg
Configuration file validation passed.
climo_atm_monthly_180x360_aave_0011-0020
Traceback (most recent call last):
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.8.0_cori-haswell/bin/zppy", line 10, in <module>
    sys.exit(main())
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.8.0_cori-haswell/lib/python3.10/site-packages/zppy/__main__.py", line 140, in main
    existing_bundles = ts(config, scriptDir, existing_bundles)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.8.0_cori-haswell/lib/python3.10/site-packages/zppy/ts.py", line 61, in ts
    machine_info = MachineInfo()
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.8.0_cori-haswell/lib/python3.10/site-packages/mache/machine_info.py", line 75, in __init__
    raise ValueError('Unable to discover machine from host name')
ValueError: Unable to discover machine from host name
(e3sm_unified_1.8.0_cori-haswell) golaz@nid00286:~/E3SM/QBO/scripts> gvim /global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.8.0_cori-haswell/lib/python3.10/site-packages/zppy/ts.py
```

Note that second failure is similar to the first one, but now occurs somewhere  else:

https://github.com/E3SM-Project/zppy/blob/06c0f20dd7d5599307542f0f98dfb77b78267b64/zppy/ts.py#L61

This is clearly a bug. It should be passing the machine name that has been declared in the [default] section. It's also strange that MachineInfo() is being called here a second time.

Secondary questions for @xylar : should mache recognize cori haswell compute nodes? (Since it's going away soon, I can live without it):

```
python
>>> import socket
>>> hostname = socket.gethostname()
>>> print(hostname)
nid00286
```

**Comment by xylar** [comment]
> Secondary questions for @xylar : should mache recognize cori haswell compute nodes?

@golaz, we could make `mache` look for the environment variable `E3SMU_MACHINE`, which is defined in E3SM-Unified.  Other than that (or a similar approach where the launching software on a login node provides the machine name in some way), I'm not aware of a consistent way to recognize our machines on their compute nodes.

**Comment by forsyth2** [comment]
> It should be passing the machine name that has been declared in the [default] section.

I just created #384 to resolve this. I was able to duplicate your 2nd error and, with the changes in this pull request, was able to successfully launch `zppy` jobs. (Note that I didn't let the jobs run to completion due to Cori's excessively long queue times.)

It's important to mention that even with setting `machine`, there's the issue of `slurm_header.sh`, which only recognizes the officially supported machines. I had to manually add in `cori-haswell` to get the jobs running.

> It's also strange that MachineInfo() is being called here a second time.

Mache was useful in a few places. See the changed lines in #384 -- usually it's to find the diagnostics base path, though in one case it's to find the web portal paths. I suppose we could create parameters in the configuration so we don't have to call Mache more than once.

**Comment by xylar** [comment]
> Mache was useful in a few places. See the changed lines in https://github.com/E3SM-Project/zppy/pull/384 -- usually it's to find the diagnostics base path, though in one case it's to find the web portal paths. I suppose we could create parameters in the configuration so we don't have to call Mache more than once.

Yes, my typical usage is that I merge `mache`'s config options with those I'm getting from other sources.  (I can do that because I'm using standard python config files.)  You could have somewhere that you set various zppy config options from their `mache` counterparts and then hopefully you're done.  You could keep the `machine_info` object if you needs something other than config options but if that's all you need, I'd copy them over and be done.

**Comment by forsyth2** [comment]
@golaz If you use a development environment with the latest `main`, you should be able to run.

**Comment by golaz** [comment]
@forsyth2 : thanks for working on this.
